### ISSUE TITLE
Q9: Entities endpoint

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#15]
- **About the sort filter:**    
There is no way to sort by more than one condition, because QueryConditions class accepts only 1 SortCondition object.    
I also cannot implement my own QueryConditions class because the problem does not resides only there, but    MongoQueryProvider only is able to handle 1  sort condition.   

You should update MongoQueryProvider and QueryCondition classes in the core jar.    

I could sort on server side using java, but  it's not a recommended practice because we could have performance issues,    and it will take me more time to implement that solution.  

- **About the offset filter:**    
If I have to handle the offset in code, I will have to put big collections in memory, because  I will have to query all documents, and store them in memory to navigate through them.   
QueryConditions already have a limit property.   
Is it possible for you to update QueryConditions and add the offset field?  

- **About joining Entities with Embroys**    Is there any way to execute an aggregate function with your core jar?    
An agregate function will allow me to join Entities with Embroys.    

Example:   

 ´´´    
db.getCollection('Entity').aggregate([  {     $lookup:      {        from: 'EmbryoEntity',        localField: 'embryoEntitiesIds',        foreignField: '_id',        as: "enti_embry"      }  } ])    
´´´    

If there is no way to execute this query, I  will have to code the JOIN, which will be expensive in terms of performance    and memory.  

- **About the fields parameter:**    
I have used the method QueryConditions.addFieldProjections(fieldstoIncludeList).    
It returns the not desired fields with null  values, does it work for you? Or do you want to remove these  fields from the Json response?   

Thanks a lot

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev 

*Sorting*:
As I alluded to in a previous issue, you don't need to support sorting on multiple fields. Feel free to return an error if someone tries to do this. We may update the core functionality later.

*Offset Filter*:

Good question. To avoid large memory usage, I would use the `MongoTemplate` APIs that return `IManagedIterator` rather than the ones that return `List`. This way, you can iterate through documents sequentially without keeping them all in memory.

I agree that doing it manually is not best practice. In the future we may update the core API to support skip/limit. For now though, let's do it manually...

*Joining Embryos With Entities*
I'd actually recommend caching all of `EmbryoEntity` in memory, except for the large fields that I mentioned (`toListIds`,`ccListIds`,`bccListIds`,`fromListIds`). In terms of memory usage it's a fairly small collection (shouldn't occupy more than 100MB even for very large datasets).

Btw, not relevant to right now, but you may have noticed that some of the `MongoTemplate` APIs return a `PCollection<T>`. These make use of the Apache Beam API (basically a wrapper over Spark). In the future, we may do joins using these (which will also limit memory usage). But for now, don't worry about it and feel free to cache EmbryoEntity.

*Fields/Null Values*

Good question. Let's remove these from the JSON response.

**Comment by leonardoauer** [comment]
@fatsmcgee 

About last point, **Fields/Null Values**
When a value is null, it won't appear in the json response even if was requested as a field. 
I'll do it this way because otherwise I will have to use reflection and make a complex logic for just a simple feature, I don't think it's worth. 

If you still want the field appear even when is null, let me know, but it will take me sometime to do it.

**Comment by fatsmcgee** [comment]
@stanstempdev @leonardoauer 

I see your point. Given that, I think returning `null` is fine... the client who requested the fields should be responsible for dealing with it.
