### ISSUE TITLE
Question 7: \entities GET request

### ISSUE THREAD

**Issue by leonardoauer** [stanstempdev/eat_api#7]
About the query parameters, the documents mentions these ones:

> limit, offset, sort and filter. 

Are there more?
Please specify all parameters, as id, etc. 

Thanks.

**Comment by fatsmcgee** [comment]
@leonardoauer @stanstempdev That is it for this API.

You mention `id` as a parameter. We don't need that right now, but might add a separated API to get individual entities later. 

Note that because `_id` is a field of `Entity` in the database, you could get a specific `Entity` with `/entities?filter='_id=the_entity_id'`
